"""add description

Revision ID: 234954b82723
Revises: acf3c10be1cd
Create Date: 2026-08-09 17:24:40.738481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234954b82723'
down_revision: Union[str, Sequence[str], None] = 'acf3c10be1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The original base revision was accidentally committed empty. Existing
    # databases may therefore report it as applied without having the table.
    # Repair those databases here; fresh databases use the corrected base.
    bind = op.get_bind()
    if not sa.inspect(bind).has_table('urls'):
        op.create_table(
            'urls',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('original_url', sa.String(), nullable=False),
            sa.Column('short_code', sa.String(), nullable=False),
            sa.Column('clicks', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.Column('description', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
        op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=True)
    else:
        op.add_column('urls', sa.Column('description', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'description')
    # ### end Alembic commands ###
